import { MEALS, localDate, dateObject, shiftDate, id, numeric, labelAmount, batchTotal, batchAmount, batchRemaining, dayFor, summary, addEntry, finishDay, parseDescription, freshState, validateBackup } from './core.js';
import { loadState, writeState, STORAGE_KEY } from './storage.js';
import { RESTAURANT_TEMPLATES, DINNER_IDEAS } from './catalog.js';

const $=s=>document.querySelector(s), app=$('#app'), modal=$('#modal');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.round(n).toLocaleString(), shortDate=d=>dateObject(d).toLocaleDateString(undefined,{month:'short',day:'numeric'});
const symbols={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',pot:'<path d="M5 9h14v8a3 3 0 0 1-3 3H8a3 3 0 0 1-3-3ZM2 11h3m14 0h3M4 6h16M9 3h6"/>',dinner:'<path d="M5 3v6m3-6v6M2 3v6a3 3 0 0 0 6 0M5 12v9M18 3c-4 4-4 10 0 10h2V3h-2Zm2 10v8"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 10h18M8 14h1m6 0h1m-8 3h1"/>',settings:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="8" cy="18" r="2"/>',back:'<path d="m14 5-7 7 7 7"/>',next:'<path d="m9 5 7 7-7 7"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',share:'<path d="M12 15V3m-4 4 4-4 4 4M5 11v9h14v-9"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M4 17v4h16v-4"/>',refresh:'<path d="M20 5v6h-6M4 19v-6h6M5 8a8 8 0 0 1 13-3l2 6M4 13l2 6a8 8 0 0 0 13-3"/>',heart:'<path d="M12 20 4 12C-2 4 8 0 12 7c4-7 14-3 8 5Z"/>',check:'<path d="m5 12 4 4L19 6"/>',edit:'<path d="m15 4 5 5M4 20l5-1L21 7l-5-5L4 14Z"/>',trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7"/>',leaf:'<path d="M4 20C1 6 9 3 21 3c0 12-3 20-17 17Zm0 0L16 8"/>',plus:'<path d="M12 5v14M5 12h14"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${symbols[n]||symbols.leaf}</svg>`;
const button=(label,action,cls='',attrs='')=>`<button type="button" class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
let state,storageError='';
try{state=loadState();}catch{state=freshState();storageError='Your saved data could not be read. It has not been overwritten. Export the stored data or explicitly reset it in Settings.';}
let ui={page:'today',date:localDate(),month:localDate().slice(0,7),selected:localDate(),tab:'describe',label:{name:'',sodium:'',amount:'1',mode:'servings',container:'',meal:mealNow(),source:'Package label',estimate:false},notice:'',historyFocus:null};
let undoState=null,toastTimer,installPrompt=null,swRegistration=null,importCandidate=null,activeBatch=null;
function mealNow(){const h=new Date().getHours();return h<11?'Breakfast':h<15?'Lunch':h<18?'Snacks':'Dinner';}
function day(){return dayFor(state,ui.date);}
function remaining(){return summary(day()).remaining;}
function after(mg){const left=remaining()-mg;return `${summary(day()).estimated?'About ':''}${fmt(Math.abs(left))} mg ${left>=0?'left after this':'over your limit after this'}`;}
function commit(fn,{undo=false}={}){
  if(storageError)throw new Error('Saved data needs attention. Open Settings before making changes.');
  const before=structuredClone(state),next=structuredClone(state);fn(next);
  try{state=writeState(next,state.revision);}catch(e){throw new Error(e.name==='QuotaExceededError'?'Device storage is full. Export a backup before clearing space. Nothing was saved.':e.message);}
  if(undo)undoState=before;
  return state;
}
function toast(message,undo=false){clearTimeout(toastTimer);$('#toast').innerHTML=`<span>${esc(message)}</span>${undo?button('Undo','undo','text-button'):''}`;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,6000);}
function go(page){ui.page=page;ui.notice='';history.replaceState(null,'',`#${page}`);render();$('#main')?.scrollTo(0,0);}
function errorMessage(e){if(modal.open){const el=modal.querySelector('.form-error');if(el){el.textContent=e.message;el.hidden=false;return;}}toast(e.message);}
function showDialog(title,body,{wide=false}={}){modal.innerHTML=`<header class="dialog-head"><h2 id="dialog-title">${esc(title)}</h2>${button(icon('close'),'close','icon-button','aria-label="Close dialog"')}</header><div class="dialog-body">${body}<p class="form-error" role="alert" hidden></p></div>`;modal.classList.toggle('wide-dialog',wide);if(!modal.open)modal.showModal();}
function closeDialog(){modal.close();}
function input(name,label,value='',{type='text',min,step='any',placeholder='',required=true,maxlength=250}={}){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${min!==undefined?`min="${min}"`:''} ${type==='number'?`step="${step}" inputmode="decimal"`:''} placeholder="${esc(placeholder)}" ${required?'required':''} maxlength="${maxlength}" autocomplete="off"></label>`;}
function mealSelect(value){return `<label>Meal<select name="meal">${MEALS.map(m=>`<option ${m===value?'selected':''}>${m}</option>`).join('')}</select></label>`;}
function fractionInput(name,label,value='1'){return input(name,label,value,{placeholder:'1, 1.5 or ½'});}
function submit(label,extra=''){return `<p class="form-error" role="alert" hidden></p><button class="primary" type="submit" ${extra}>${label}</button>`;}
function dayHeading(){return `<div class="page-heading"><h1>${ui.date===localDate()?'Today':shortDate(ui.date)}</h1><div class="date-controls">${button(icon('back'),'previous-day','icon-button','aria-label="Previous day"')}<button class="date-button" data-action="pick-date">${esc(dateObject(ui.date).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}))}</button>${button(icon('next'),'next-day','icon-button',`aria-label="Next day" ${ui.date>=localDate()?'disabled':''}`)}</div></div>`;}
function todayView(){
  const d=day(),s=summary(d);
  return `<section class="today-view">${dayHeading()}<div class="allowance ${s.remaining<0?'over':''}" aria-label="Daily sodium summary"><div class="allowance-top"><span>${s.estimated?'Estimated ':''}${s.remaining<0?'over your limit':'remaining today'}</span><span class="tiny-pill">${fmt(d.goal)} mg limit</span></div><div class="allowance-number">${fmt(Math.abs(s.remaining))}<span>mg</span></div><div class="meter" role="progressbar" aria-label="Sodium logged" aria-valuemin="0" aria-valuemax="${d.goal}" aria-valuenow="${Math.min(d.goal,s.total)}" aria-valuetext="${fmt(s.total)} mg logged of ${fmt(d.goal)} mg"><span style="width:${Math.min(100,s.total/d.goal*100)}%"></span></div><div class="allowance-bottom"><span>${s.estimated?'~':''}${fmt(s.total)} mg logged</span><span>${s.count?`${s.count} food${s.count===1?'':'s'}`:'A fresh page 🍊'}</span></div></div><div class="section-heading"><h2>Your meals</h2><span class="muted small">Tap for details</span></div><div class="meal-list">${MEALS.map(m=>{const items=d.entries.filter(e=>e.meal===m),total=items.reduce((a,e)=>a+e.mg,0);return `<details class="meal-group"><summary><span>${m}</span><span class="meal-total">${items.length?`${items.some(e=>e.estimate)?'~':''}${fmt(total)} mg`:'—'}${icon('next')}</span></summary><div class="meal-items">${items.length?items.map(e=>`<button class="food-row" data-action="edit-entry" data-id="${esc(e.id)}"><span>${esc(e.name)}<small>${esc(e.source||'Entered by you')}${e.quantityLabel?' · '+esc(e.quantityLabel):''}</small></span><span>${e.estimate?'~':''}${fmt(e.mg)} mg ${icon('edit')}</span></button>`).join(''):`<p class="muted small">Nothing here yet. ${button('Add food','add-meal','inline-button',`data-meal="${m}"`)}</p>`}</div></details>`;}).join('')}</div>${d.plan?`<button class="plan-strip" data-action="show-plan"><span>Planned · ${esc(d.plan.name)}</span><span>~${fmt(d.plan.mg)} mg →</span></button>`:''}<div class="day-end"><div>${button(`${s.status==='within'?'🌼':s.status==='over'?'☁️':'🌼'} ${d.complete?'Day finished':'Finish today’s log'}`,'finish','finish-button',s.count?'':'disabled')}<p class="muted small">${!s.count?'Start with your first food.':d.complete?'A little more clarity. Nicely logged.':'All meals entered? Collect your sticker.'}</p></div></div></section>`;
}
function addView(){return `<section><div class="eyebrow">A quick addition · ${esc(shortDate(ui.date))}</div><h1>What did you have?</h1><div class="tabs" role="tablist" aria-label="Entry method">${[['describe','Describe'],['label','Package label'],['out','Eating out'],['recent','Recent']].map(([key,label])=>`<button role="tab" aria-selected="${key===ui.tab}" data-action="entry-tab" data-tab="${key}">${label}</button>`).join('')}</div>${ui.notice?`<p class="notice" role="status">${esc(ui.notice)}</p>`:''}${ui.tab==='describe'?describeView():ui.tab==='label'?labelView():ui.tab==='out'?restaurantView():recentView()}</section>`;}
function describeView(){return `<form id="describe-form"><label for="description">Type or use your keyboard microphone</label><textarea id="description" name="description" required maxlength="2000" placeholder="Crackers, 180 mg per serving. I ate one and a half servings.">${esc(ui.description||'')}</textarea><p class="muted small">Tap the microphone on your phone’s keyboard to dictate.</p><details class="help"><summary>What can I say?</summary><p>“Soup, 140 mg per serving, 4 servings in the carton. I ate the whole carton.”</p><p>Include the sodium amount from your label. You’ll review the numbers before saving.</p></details>${submit('Review entry')}</form><div class="section-heading"><h2>Already know the numbers?</h2></div>${button('Enter the label directly →','entry-tab','text-button','data-tab="label"')}`;}
function labelView(){const x=ui.label;return `<form id="label-form" data-calculator="label">${input('name','Food name',x.name)}<div class="two-columns">${input('sodium','Sodium per label serving (mg)',x.sodium,{type:'number',min:0})}<label>Amount is in<select name="mode"><option value="servings" ${x.mode==='servings'?'selected':''}>Label servings</option><option value="containers" ${x.mode==='containers'?'selected':''}>Whole containers</option></select></label></div><div class="two-columns">${fractionInput('amount',x.mode==='containers'?'Containers eaten':'Servings eaten',x.amount)}<label data-container-field ${x.mode==='containers'?'':'hidden'}>Label servings per container<input name="container" inputmode="decimal" value="${esc(x.container)}" placeholder="e.g. 4"></label></div>${mealSelect(x.meal)}<label class="check"><input type="checkbox" name="estimate" ${x.estimate?'checked':''}>This sodium amount is an estimate</label><div class="result" data-result aria-live="polite"></div><label class="check"><input type="checkbox" name="favorite">Save to my usual foods</label>${submit('Add food')}</form>`;}
function restaurantView(){return `<p class="muted">Choose a reference or enter a restaurant’s published nutrition. Always review portions and extras.</p><form id="restaurant-form" data-calculator="restaurant"><label>Dish reference<select name="template">${RESTAURANT_TEMPLATES.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label>${input('name','Restaurant / dish','Chicken rice bowl')}${input('sodium','Sodium for the whole dish (mg)',1020,{type:'number',min:0})}${fractionInput('amount','How much of the dish did you eat?','1')}<p class="muted small">1 = whole dish · ½ = half</p>${mealSelect(ui.label.meal)}<div class="notice" id="restaurant-basis"></div><label class="check"><input type="checkbox" name="published">I verified this against the restaurant’s current nutrition</label><div class="result" data-result aria-live="polite"></div>${submit('Review and log portion')}</form>`;}
function recentView(){const recent=Object.values(state.days).flatMap(d=>d.entries).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));const foods=[...state.favorites,...recent].filter((e,i,arr)=>arr.findIndex(v=>v.name===e.name&&v.mg===e.mg)===i).slice(0,20);return foods.length?`<p class="muted small">Tap to review and log again.</p><div class="list">${foods.map((e,i)=>`<button class="choice-row" data-action="reuse" data-index="${i}"><span>${esc(e.name)}<small>${esc(e.quantityLabel||e.source)}</small></span><span>${e.estimate?'~':''}${fmt(e.mg)} mg ${icon('next')}</span></button>`).join('')}</div>`:`<div class="empty"><span class="empty-sticker">🍊</span><h2>Your usuals will live here.</h2><p>Log a food once, then bring it back with a tap.</p></div>`;}
function kitchenView(){return `<section><div class="eyebrow">In the kitchen</div><h1>Good things together.</h1><p class="muted">Build the whole dish. Log only your share.</p>${button(`${icon('plus')} ${state.draft?'Continue cooking':'Make a dish'}`,'new-batch','primary')}<div class="section-heading"><h2>Your batches</h2><span class="muted small">Ready for leftovers</span></div>${state.batches.length?state.batches.slice().reverse().map(b=>{const rest=batchRemaining(state,b);return `<article class="card"><div class="row"><span class="tag">${rest>0?'In your kitchen':'All logged'}</span><span class="muted small">${shortDate(b.date)}</span></div><h3>${esc(b.name)}</h3><p class="muted small">${fmt(batchTotal(b.ingredients))} mg in the batch · ${b.yield} portions</p><div class="batch-number">${fmt(batchTotal(b.ingredients)/b.yield)}<small>mg / portion</small></div><p class="muted small">${rest} portion${rest===1?'':'s'} left to log</p><div class="two-actions">${button('Log a portion','portion','secondary',`data-id="${esc(b.id)}" ${rest>0?'':'disabled'}`)}${button('Cook again','clone-batch','text-button',`data-id="${esc(b.id)}"`)}</div></article>`;}).join(''):`<div class="empty"><span class="empty-sticker">🥣</span><h2>One pot. All figured out.</h2><p>Add the broth, beans, seasoning—everything that goes in. We’ll take care of the portion math.</p></div>`}</section>`;}
function draftView(){const b=state.draft||{name:'',yield:4,ingredients:[]};let total=0;try{total=batchTotal(b.ingredients);}catch{}return `<section><div class="row">${button('‹ My kitchen','page','text-button','data-page="cook"')}${button('Discard draft','discard-draft','text-button danger')}</div><h1>Build your dish.</h1><form id="batch-form">${input('name','Dish name',b.name,{placeholder:'e.g. Vegetable soup'})}<div class="ingredient-list">${b.ingredients.map((i,index)=>`<div class="ingredient-row"><div><strong>${esc(i.name)}</strong><small>${i.amount} ${i.mode==='containers'?`container${i.amount===1?'':'s'} × ${i.container} servings`:'label servings'} × ${fmt(i.sodium)} mg</small></div><span>${fmt(labelAmount(i.sodium,i.amount,i.mode,i.container))} mg</span>${button(icon('edit'),'edit-ingredient','icon-button',`data-index="${index}" aria-label="Edit ${esc(i.name)}"`)}${button(icon('trash'),'remove-ingredient','icon-button',`data-index="${index}" aria-label="Remove ${esc(i.name)}"`)}</div>`).join('')}</div>${button(`${icon('plus')} Add ingredient`,'ingredient','secondary full')}<div class="result"><div class="row"><span>Whole dish</span><strong>${fmt(total)} mg</strong></div></div>${input('yield','How many equal portions does this make?',b.yield,{type:'number',min:.001})}<p class="muted small">You can log a fraction of a portion later. Saving a batch does not add it to your daily log.</p>${submit('Save batch')}</form></section>`;}
function dinnerView(){const available=remaining()-state.preferences.reserve;const ideas=DINNER_IDEAS.filter(r=>!state.preferences.vegetarian||r.vegetarian).map(r=>({...r,batch:false}));for(const b of state.batches){if(batchRemaining(state,b)>=1){const mg=batchTotal(b.ingredients)/b.yield;ideas.unshift({id:b.id,name:b.name,emoji:'🥣',minutes:5,mg,high:mg,low:mg,batch:true});}}
  ideas.sort((a,b)=>Number(b.high<=available)-Number(a.high<=available)||a.high-b.high);
  return `<section><div class="eyebrow">Tonight, made easier</div><h1>Room for dinner.</h1><p class="muted">${summary(day()).estimated?'About ':''}${fmt(Math.abs(remaining()))} mg ${remaining()>=0?'remaining':'over your daily limit'}.</p><details class="help"><summary>Dinner preferences</summary><form id="dinner-preferences"><label class="check"><input name="vegetarian" type="checkbox" ${state.preferences.vegetarian?'checked':''}>Vegetarian suggestions</label>${input('reserve','Leave room for later (mg)',state.preferences.reserve,{type:'number',min:0})}${submit('Save preferences')}</form></details>${day().plan?`<div class="notice"><span class="eyebrow">Planned, not yet eaten</span><h3>${esc(day().plan.name)}</h3><p>~${fmt(day().plan.mg)} mg · ${after(day().plan.mg)}</p>${button('Review plan','show-plan','text-button')}</div>`:''}<div class="recipe-list">${ideas.map(r=>`<article class="card recipe-card"><div class="row"><span class="tag">${r.batch?'From your kitchen':r.high<=available?'Room in your allowance':'Review the portion'}</span><span class="muted small">${r.minutes} min</span></div><h3><span aria-hidden="true">${r.emoji}</span> ${esc(r.name)}</h3><div class="batch-number">${r.batch?'':'~'}${fmt(r.mg)}<small>mg / portion</small></div><p class="muted small">${r.batch?after(r.mg):`Planning range ${r.low}–${r.high} mg. ${r.high<=available?'Upper estimate leaves room.':'May exceed your dinner allowance.'}`}</p>${button(r.batch?'Choose my portion':'See ingredients','recipe','secondary full',`data-id="${esc(r.id)}" data-batch="${r.batch}"`)}</article>`).join('')}</div><p class="muted small">Ideas use estimated ingredients, not a guarantee. Check labels and count sauces, salt and any changes.</p></section>`;
}
const sticker={empty:'·',progress:'✏️',within:'🌼',over:'☁️'},statusName={empty:'No log',progress:'Still logging',within:'Within limit',over:'Over limit'};
function calendarView(){const [y,m]=ui.month.split('-').map(Number),count=new Date(y,m,0).getDate(),offset=(new Date(y,m-1,1).getDay()+6)%7;const selected=dayFor(state,ui.selected),s=summary(selected),dateTitle=dateObject(ui.selected).toLocaleDateString(undefined,{month:'long',day:'numeric'});return `<section><div class="eyebrow">Your little collection</div><h1>Every log tells a story.</h1><div class="month-heading">${button(icon('back'),'previous-month','icon-button','aria-label="Previous month"')}<h2>${new Date(y,m-1,1).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2>${button(icon('next'),'next-month','icon-button',`aria-label="Next month" ${ui.month>=localDate().slice(0,7)?'disabled':''}`)}</div><div class="weekdays" aria-hidden="true">${['M','T','W','T','F','S','S'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid" aria-label="Logging calendar">${'<span></span>'.repeat(offset)}${Array.from({length:count},(_,i)=>{const date=`${ui.month}-${String(i+1).padStart(2,'0')}`,d=dayFor(state,date),v=summary(d);return `<button class="calendar-day ${date===localDate()?'is-today':''}" data-action="select-day" data-date="${date}" aria-pressed="${ui.selected===date}" ${date>localDate()?'disabled':''} aria-label="${date}: ${statusName[v.status]}${v.estimated?', estimated':''}"><span>${i+1}</span><span class="sticker" aria-hidden="true">${date>localDate()?'':sticker[v.status]}</span></button>`;}).join('')}</div><div class="calendar-legend"><span>🌼 Within limit</span><span>☁️ Over limit</span><span>✏️ Still logging</span><span>· No log</span></div><div class="card day-detail ${selected.complete?'celebrate':''}"><h3>${sticker[s.status]} ${dateTitle}</h3><p class="muted">${s.count?`${s.estimated?'Estimated: ':''}${fmt(s.total)} mg · ${fmt(selected.goal)} mg limit. ${statusName[s.status]}.`:'No food logged. A blank day is not a missed goal.'}</p>${button(s.count?'View or edit this day':'Log this day','view-day','text-button',`data-date="${ui.selected}"`)}</div><div class="row">${button('Jump to today','calendar-today','text-button')}<span class="muted small">${Object.values(state.days).filter(d=>d.complete&&d.entries.length).length} days collected</span></div><p class="muted small">Finish your log to earn a sticker. Each day keeps its own limit; estimates stay estimates.</p></section>`;}
function settingsView(){return `<section><div class="eyebrow">The little details</div><h1>Make yourself at home.</h1>${storageError?`<p class="notice danger">${esc(storageError)}</p>`:''}<div class="list">${settingsRow('Daily sodium limit',`${fmt(state.goal)} mg / day`,'goal','sun')}${settingsRow('Add to Home Screen',isStandalone()?'Already installed':'Your own little shortcut','install','download')}${settingsRow('Refresh data','Keep every entry','refresh','refresh')}${settingsRow('Share app','Invite friends and family','share','heart')}${settingsRow('Export backup','Save your private log as a file','export','download')}${settingsRow('Import backup','Restore a saved log','import','refresh')}${settingsRow('Reset tracking data','Clear logs, recipes and stickers','reset','trash')}</div><label>Appearance<select id="theme-select"><option value="system" ${state.preferences.theme==='system'?'selected':''}>Match my phone</option><option value="light" ${state.preferences.theme==='light'?'selected':''}>Tangerine & butter</option><option value="dark" ${state.preferences.theme==='dark'?'selected':''}>Warm evening</option></select></label><div class="privacy-note"><h2>Just yours.</h2><p>Your log is stored in this browser on this device. No account, analytics or paid voice service. Clearing browser data removes it, so keep a backup. Other devices have separate logs.</p><span class="small muted">a little less · v1.0.0</span></div><input id="import-file" type="file" accept="application/json,.json" hidden></section>`;}
function settingsRow(title,sub,action,i){return `<button class="settings-row" data-action="${action}"><span class="settings-icon">${icon(i)}</span><span>${title}<small>${esc(sub)}</small></span>${icon('next')}</button>`;}
function render(){
  document.documentElement.dataset.theme=state.preferences.theme;document.querySelector('meta[name="theme-color"]').content=state.preferences.theme==='dark'?'#261c18':'#fff8f0';
  const views={today:todayView,add:addView,cook:kitchenView,draft:draftView,dinner:dinnerView,calendar:calendarView,settings:settingsView};
  if(!views[ui.page])ui.page='today';
  app.innerHTML=`<div class="app-shell"><header class="app-header"><button class="wordmark" data-action="page" data-page="today" aria-label="a little less, Today">a little less<span class="brand-orange" aria-hidden="true"></span></button><div class="header-actions">${!navigator.onLine?'<span class="offline-label">Offline</span>':''}${button(icon('settings'),'page','icon-button',`data-page="settings" aria-label="Settings"`)}</div></header><main id="main" class="${ui.page==='today'?'home-main':''}" tabindex="-1">${views[ui.page]()}</main><div class="bottom-area">${['today','cook','dinner','calendar'].includes(ui.page)?button('+','add','fab','aria-label="Add food"'):''}<nav aria-label="Main navigation">${[['today','sun','Today'],['cook','pot','Cooking'],['dinner','dinner','Dinner ideas'],['calendar','calendar','Stickers']].map(([p,i,label])=>`<button data-action="page" data-page="${p}" ${ui.page===p||p==='cook'&&ui.page==='draft'?'aria-current="page"':''}>${icon(i)}<span>${label}</span></button>`).join('')}</nav></div></div>`;
  if(ui.page==='add'&&ui.tab==='label')updateCalculator($('#label-form'));
  if(ui.page==='add'&&ui.tab==='out')updateRestaurant();
}
function formData(form){return Object.fromEntries(new FormData(form));}
function updateCalculator(form){if(!form)return;const d=formData(form),out=form.querySelector('[data-result]');if(!out)return;try{const mg=form.id==='restaurant-form'?labelAmount(d.sodium,d.amount):labelAmount(d.sodium,d.amount,d.mode,d.container);out.innerHTML=`<div class="row"><span>${form.id==='ingredient-form'?'Added to whole dish':'Your portion'}</span><strong>${d.estimate||form.id==='restaurant-form'&&!d.published?'~':''}${fmt(mg)} mg</strong></div><p class="muted small">${form.id==='ingredient-form'?'Counts toward the batch, not today’s log.':after(mg)}</p>`;}catch{out.innerHTML='<p class="muted small">Enter the label and portion to see the total.</p>';}}
function updateRestaurant(){const form=$('#restaurant-form');if(!form)return;const t=RESTAURANT_TEMPLATES.find(t=>t.id===form.elements.template.value);form.elements.name.value=t.id==='custom'?'':t.name;form.elements.sodium.value=t.mg??'';form.elements.published.checked=false;$('#restaurant-basis').innerHTML=`<p>${esc(t.basis)}</p>${t.url?`<p class="small">Rough planning range: ${t.low}–${t.high} mg for the whole dish (not a statistical confidence interval).</p><a href="${t.url}" target="_blank" rel="noopener noreferrer">${esc(t.source)} ↗</a>`:''}`;updateCalculator(form);}
function logFood(entry,favorite=false){commit(s=>{addEntry(s,ui.date,entry);if(favorite){s.favorites=s.favorites.filter(e=>e.name!==entry.name);s.favorites.push({...entry,id:id()});}},{undo:true});closeDialog();go('today');toast(`${entry.name} added. A little more clarity.`,true);}
function openIngredient(index=null){const i=index!==null?state.draft.ingredients[index]:{name:'',sodium:'',amount:1,mode:'servings',container:''};showDialog(index!==null?'Edit ingredient':'Add to the pot',`<form id="ingredient-form" data-index="${index??''}" data-calculator="ingredient">${input('name','Ingredient',i.name)}${input('sodium','Sodium per label serving (mg)',i.sodium,{type:'number',min:0})}<label>Amount added in<select name="mode"><option value="servings" ${i.mode==='servings'?'selected':''}>Label servings</option><option value="containers" ${i.mode==='containers'?'selected':''}>Whole containers / cartons</option></select></label><div class="two-columns">${fractionInput('amount','Amount added',i.amount)}${input('container','Label servings / container',i.container,{required:false,placeholder:'Only for containers'})}</div><div class="result" data-result></div>${submit(index!==null?'Save ingredient':'Add ingredient')}</form>`);updateCalculator($('#ingredient-form'));}
function openPortion(batchId){activeBatch=state.batches.find(b=>b.id===batchId);if(!activeBatch)throw new Error('That batch was not found.');const rest=batchRemaining(state,activeBatch);showDialog(activeBatch.name,`<p class="muted">${rest} of ${activeBatch.yield} portions left to log.</p><form id="portion-form">${fractionInput('portions','Your portions',Math.min(1,rest))}${mealSelect('Dinner')}<div class="result" id="portion-result"></div>${submit('Log my portion')}</form>`);updatePortion();}
function updatePortion(){const f=$('#portion-form');if(!f)return;try{const qty=numeric(f.elements.portions.value,'Portions',{min:.001}),mg=batchAmount(activeBatch,qty);if(qty>batchRemaining(state,activeBatch))throw new Error('That is more than the remaining batch.');$('#portion-result').innerHTML=`<strong>${fmt(mg)} mg</strong><p class="muted small">${after(mg)}</p>`;}catch(e){$('#portion-result').textContent=e.message;}}
function openRecipe(recipeId,isBatch){if(isBatch){openPortion(recipeId);return;}const r=DINNER_IDEAS.find(r=>r.id===recipeId);if(!r)return;showDialog(r.name,`<span class="tag">Planning estimate · ${r.minutes} minutes</span><p class="recipe-sodium">~${r.mg} mg <small>per portion · range ${r.low}–${r.high}</small></p><ul class="ingredient-notes">${r.ingredients.map(i=>`<li>${esc(i)}</li>`).join('')}</ul><p>${esc(r.steps)}</p><p class="muted small">${esc(r.basis)}</p><form id="plan-form" data-id="${esc(r.id)}">${fractionInput('portions','Portions to plan','1')}${submit('Plan this dinner')}</form>`);}
function openPlan(){const p=day().plan;if(!p)return;showDialog('Tonight’s plan',`<h3>${esc(p.name)}</h3><p>~${fmt(p.mg)} mg · ${esc(p.portions)} portion${p.portions===1?'':'s'}</p><p class="muted small">Only log this if you ate the planned ingredients and portion. Check any changes first.</p>${button('I ate this · review & log','log-plan','primary')}${button('Remove plan','remove-plan','text-button')}`);}
function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;}
function installView(){showDialog(isStandalone()?'You’re home.':'A little home on your phone.',`${icon('leaf')}<p>Add a shortcut to open your tracker in its own window.</p>${isStandalone()?'<p class="notice">This app is already running from your Home Screen.</p>':installPrompt?button('Install a little less','install-now','primary'):''}<h3>iPhone / iPad</h3><ol><li>Open this app in Safari.</li><li>Tap Share, then <strong>Add to Home Screen</strong>.</li><li>Enable <strong>Open as Web App</strong> if offered, then tap Add.</li></ol><h3>Android</h3><p>Open Chrome’s menu and choose <strong>Install app</strong> or <strong>Add to Home screen</strong>.</p><p class="muted small">Installation requires HTTPS (or localhost for development). Availability depends on your browser. Once opened online, the tracker can work offline.</p>`);}
function shareUrl(){return `${location.origin}${location.pathname}`;}
async function shareApp(){if(['localhost','127.0.0.1'].includes(location.hostname)){showDialog('Ready to share soon',`<p>This is a local development address. Publish the app to an HTTPS address so friends and family can open it on their phones.</p><p class="muted small">Sharing sends only the app link, never your food log.</p>`);return;}const data={title:'a little less',text:'A little clarity, one meal at a time. 🍊',url:shareUrl()};if(navigator.share){try{await navigator.share(data);return;}catch(e){if(e.name==='AbortError')return;}}showDialog('Share a little love',`<p>Share the app, never your private food log.</p><label>App link<input id="share-link" readonly value="${esc(data.url)}"></label>${button('Copy link','copy-link','primary')}`);}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function openGoal(){showDialog('Your daily sodium limit',`<form id="goal-form">${input('goal','Daily limit (mg)',state.goal,{type:'number',min:1,step:1})}<p class="muted small">Use the limit you follow. Changes apply to today and future days; previous days keep their saved limits.</p>${submit('Save limit')}</form>`);}
function openEntry(entryId){const e=day().entries.find(e=>e.id===entryId);if(!e)return;showDialog(e.name,`<form id="edit-form" data-id="${esc(e.id)}">${input('name','Food',e.name)}${input('mg','Sodium in the portion you ate (mg)',e.mg,{type:'number',min:0})}${mealSelect(e.meal)}<label class="check"><input type="checkbox" name="estimate" ${e.estimate?'checked':''}>Estimated amount</label><p class="muted small">${esc(e.quantityLabel||'')}${e.batchId?' · Batch allocation stays the same. To change the portion size, delete and log it again.':''}</p>${submit('Save changes')}${button('Delete entry','delete-entry','text-button danger',`data-id="${esc(e.id)}"`)}</form>`);}
const actions={
  page:b=>go(b.dataset.page),add:()=>{ui.label.meal=mealNow();go('add');},'add-meal':b=>{ui.label.meal=b.dataset.meal;go('add');},close:closeDialog,
  'previous-day':()=>{ui.date=shiftDate(ui.date,-1);render();},'next-day':()=>{if(ui.date<localDate()){ui.date=shiftDate(ui.date,1);render();}},
  'pick-date':()=>showDialog('Choose a day',`<form id="date-form"><label>Date<input name="date" type="date" value="${ui.date}" max="${localDate()}" required></label>${submit('Open day')}</form>`),
  'entry-tab':b=>{ui.tab=b.dataset.tab;render();},'edit-entry':b=>openEntry(b.dataset.id),
  'delete-entry':b=>{commit(s=>{const d=s.days[ui.date];d.entries=d.entries.filter(e=>e.id!==b.dataset.id);d.complete=false;},{undo:true});closeDialog();render();toast('Entry removed.',true);},
  undo:()=>{if(!undoState)return;const snapshot=structuredClone(undoState);state=writeState(snapshot,state.revision);undoState=null;$('#toast').hidden=true;render();},
  finish:()=>{if(day().complete){showDialog('Day already finished',`<p>Your sticker is saved. Editing or adding food reopens the day.</p>${button('View my sticker','view-sticker','primary')}`);return;}commit(s=>finishDay(s,ui.date));ui.selected=ui.date;ui.month=ui.date.slice(0,7);go('calendar');toast(summary(day()).status==='within'?'🌼 A flower for your collection.':'☁️ Thanks for showing up and logging.');},
  'view-sticker':()=>{closeDialog();ui.selected=ui.date;ui.month=ui.date.slice(0,7);go('calendar');},
  'new-batch':()=>{if(!state.draft)commit(s=>s.draft={name:'',yield:4,ingredients:[]});go('draft');},
  ingredient:()=>openIngredient(),'edit-ingredient':b=>openIngredient(Number(b.dataset.index)),
  'remove-ingredient':b=>{commit(s=>s.draft.ingredients.splice(Number(b.dataset.index),1));render();},
  'discard-draft':()=>showDialog('Discard this cooking draft?',`<p>Your saved batches and food log won’t change.</p>${button('Keep cooking','close','primary')}${button('Discard draft','confirm-discard','text-button danger')}`),
  'confirm-discard':()=>{commit(s=>s.draft=null);closeDialog();go('cook');},
  portion:b=>openPortion(b.dataset.id),
  'clone-batch':b=>{if(state.draft)throw new Error('Finish or discard your current cooking draft first.');const recipe=state.batches.find(v=>v.id===b.dataset.id);commit(s=>s.draft={name:recipe.name,yield:recipe.yield,ingredients:structuredClone(recipe.ingredients)});go('draft');},
  recipe:b=>openRecipe(b.dataset.id,b.dataset.batch==='true'),'show-plan':openPlan,
  'remove-plan':()=>{commit(s=>(s.days[ui.date] ||= dayFor(s,ui.date)).plan=null);closeDialog();render();},
  'log-plan':()=>{const p=day().plan;showDialog('Review dinner',`<form id="log-plan-form">${input('name','Meal',p.name)}${input('mg','Sodium for your portion (mg)',p.mg,{type:'number',min:0})}<p class="muted small">Logged as an estimate. Include any extra sauce, salt or changed portions.</p>${submit('Add to dinner')}</form>`);},
  'previous-month':()=>{const [y,m]=ui.month.split('-').map(Number);ui.month=localDate(new Date(y,m-2,1)).slice(0,7);ui.selected=ui.month+'-01';render();},
  'next-month':()=>{if(ui.month>=localDate().slice(0,7))return;const [y,m]=ui.month.split('-').map(Number);ui.month=localDate(new Date(y,m,1)).slice(0,7);ui.selected=ui.month+'-01';render();},
  'select-day':b=>{ui.selected=b.dataset.date;render();},'calendar-today':()=>{ui.month=localDate().slice(0,7);ui.selected=localDate();render();},'view-day':b=>{ui.date=b.dataset.date;go('today');},
  goal:openGoal,install:installView,'install-now':async()=>{if(!installPrompt)return;await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;closeDialog();},share:shareApp,
  'copy-link':async()=>{try{await navigator.clipboard.writeText(shareUrl());toast('App link copied.');}catch{$('#share-link').select();toast('Select and copy the link above.');}},
  refresh:async()=>{state=loadState();storageError='';undoState=null;if(swRegistration){await swRegistration.update().catch(()=>{});const worker=swRegistration.installing;if(worker)await new Promise(resolve=>{const done=()=>{if(['installed','redundant'].includes(worker.state)){clearTimeout(timer);worker.removeEventListener('statechange',done);resolve();}};const timer=setTimeout(()=>{worker.removeEventListener('statechange',done);resolve();},10000);worker.addEventListener('statechange',done);done();});}if(swRegistration?.waiting){showDialog('A fresh version is ready',`<p>Your saved log stays on this device.</p>${button('Update app','update-app','primary')}`);}else{render();toast('Refreshed. Your entries are right where you left them.');}},
  'update-app':()=>{swRegistration?.waiting?.postMessage({type:'SKIP_WAITING'});},
  export:()=>{const content=storageError?localStorage.getItem(STORAGE_KEY)||'{}':JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2);download(`a-little-less-${localDate()}.json`,content,'application/json');toast('Backup downloaded. Keep it somewhere private.');},
  import:()=>$('#import-file').click(),
  'confirm-import':()=>{if(!importCandidate)return;state=writeState(importCandidate,state.revision);storageError='';importCandidate=null;closeDialog();go('today');toast('Backup restored. Welcome back.');},
  reset:()=>showDialog('A clean page?',`<p>This removes <strong>all food logs, stickers, saved batches, usual foods and dinner plans</strong> from this device. Your daily limit stays.</p><p>It can’t be undone. Export a backup first if you want to keep a copy.</p>${button('Keep my data','close','primary')}${button('Export backup','export','secondary full')}${button('Reset all tracking data','confirm-reset','text-button danger')}`),
  'confirm-reset':()=>{const next=freshState(state.goal);next.onboarded=true;next.preferences=state.preferences;if(storageError){localStorage.setItem(STORAGE_KEY,JSON.stringify({...next,revision:id()}));state=loadState();storageError='';}else state=writeState(next,state.revision);undoState=null;ui.date=localDate();closeDialog();go('today');toast('A clean page. Start whenever you’re ready. 🍊');},
  reuse:b=>{const all=Object.values(state.days).flatMap(d=>d.entries).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||'')),foods=[...state.favorites,...all].filter((e,i,a)=>a.findIndex(v=>v.name===e.name&&v.mg===e.mg)===i);const e=foods[Number(b.dataset.index)];ui.label={name:e.name,sodium:e.mg,amount:1,mode:'servings',container:'',meal:mealNow(),source:e.source,estimate:e.estimate};ui.tab='label';ui.notice='The amount below is for the portion you logged before. Review it before adding.';render();}
};
document.addEventListener('click',async event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;try{await actions[b.dataset.action]?.(b);}catch(e){errorMessage(e);}});
document.addEventListener('submit',event=>{const f=event.target;if(!(f instanceof HTMLFormElement))return;event.preventDefault();try{const d=formData(f);switch(f.id){
  case 'onboarding-form':commit(s=>{s.goal=numeric(d.goal,'Daily limit',{min:1,max:100000});s.onboarded=true;});closeDialog();render();toast('Make yourself at home. 🍊');break;
  case 'describe-form':{ui.description=d.description;const result=parseDescription(d.description);if(result.error)throw new Error(result.error);ui.label={...ui.label,...result,source:'Label from your description',estimate:false};ui.tab='label';ui.notice=['Check the numbers before saving.',...result.warnings].join(' ');render();break;}
  case 'label-form':{const mg=labelAmount(d.sodium,d.amount,d.mode,d.container);const entry={name:d.name,mg,meal:d.meal,estimate:Boolean(d.estimate),source:ui.label.source||'Package label',quantityLabel:`${d.amount} ${d.mode==='containers'?'containers':'servings'} × ${d.sodium} mg${d.mode==='containers'?` × ${d.container} servings/container`:''}`};logFood(entry,Boolean(d.favorite));break;}
  case 'restaurant-form':{const t=RESTAURANT_TEMPLATES.find(t=>t.id===d.template);logFood({name:d.name,mg:labelAmount(d.sodium,d.amount),meal:d.meal,estimate:!d.published,source:d.published?'Restaurant nutrition (verified by you)':'Restaurant estimate',quantityLabel:`${d.amount} of dish`,notes:t.basis});break;}
  case 'edit-form':commit(s=>{const e=s.days[ui.date].entries.find(e=>e.id===f.dataset.id);if(!d.name.trim())throw new Error('Give your food a name.');Object.assign(e,{name:d.name.trim(),mg:numeric(d.mg,'Sodium'),meal:d.meal,estimate:Boolean(d.estimate)});s.days[ui.date].complete=false;},{undo:true});closeDialog();render();toast('Entry updated.',true);break;
  case 'ingredient-form':{const item={name:d.name.trim(),sodium:numeric(d.sodium,'Sodium'),amount:numeric(d.amount,'Amount',{min:.001}),mode:d.mode,container:d.mode==='containers'?numeric(d.container,'Servings per container',{min:.001}):1};if(!item.name)throw new Error('Name the ingredient.');labelAmount(item.sodium,item.amount,item.mode,item.container);commit(s=>{if(f.dataset.index==='')s.draft.ingredients.push(item);else s.draft.ingredients[Number(f.dataset.index)]=item;});closeDialog();render();break;}
  case 'batch-form':{if(!d.name.trim())throw new Error('Name your dish.');batchTotal(state.draft.ingredients);const batch={...structuredClone(state.draft),name:d.name.trim(),yield:numeric(d.yield,'Batch portions',{min:.001}),id:id(),date:localDate()};commit(s=>{s.batches.push(batch);s.draft=null;});go('cook');toast('Batch saved. Your portion is ready when you are.');break;}
  case 'portion-form':{const qty=numeric(d.portions,'Portions',{min:.001});if(qty>batchRemaining(state,activeBatch))throw new Error('That is more than the remaining batch.');logFood({name:activeBatch.name,mg:batchAmount(activeBatch,qty),meal:d.meal,estimate:activeBatch.ingredients.some(i=>i.estimate),source:'Your recipe',batchId:activeBatch.id,portions:qty,quantityLabel:`${qty} of ${activeBatch.yield} portions`});break;}
  case 'plan-form':{const r=DINNER_IDEAS.find(r=>r.id===f.dataset.id),portions=numeric(d.portions,'Portions',{min:.001});commit(s=>(s.days[ui.date] ||= dayFor(s,ui.date)).plan={name:r.name,mg:r.mg*portions,portions,recipeId:r.id});closeDialog();render();toast('Dinner planned. It’s not logged as eaten.');break;}
  case 'log-plan-form':{const entry={name:d.name,mg:numeric(d.mg,'Sodium'),meal:'Dinner',estimate:true,source:'Recipe planning estimate'};commit(s=>{addEntry(s,ui.date,entry);s.days[ui.date].plan=null;},{undo:true});closeDialog();go('today');toast('Dinner added.',true);break;}
  case 'goal-form':commit(s=>{s.goal=numeric(d.goal,'Daily limit',{min:1,max:100000});const today=s.days[localDate()];if(today){today.goal=s.goal;today.complete=false;}});closeDialog();render();toast('Daily limit updated.');break;
  case 'dinner-preferences':commit(s=>{s.preferences.reserve=numeric(d.reserve,'Reserve',{max:100000});s.preferences.vegetarian=Boolean(d.vegetarian);});render();break;
  case 'date-form':if(d.date>localDate()||!d.date)throw new Error('Choose today or an earlier date.');ui.date=d.date;closeDialog();go('today');break;
}}catch(e){const out=f.querySelector('.form-error');if(out){out.textContent=e.message;out.hidden=false;}else errorMessage(e);}});
document.addEventListener('input',event=>{const f=event.target.closest('form');if(!f)return;if(f.dataset.calculator){if(f.id==='label-form'){const d=formData(f);ui.label={...ui.label,...d,estimate:Boolean(d.estimate)};const field=f.querySelector('[data-container-field]');field.hidden=d.mode!=='containers';f.elements.amount.closest('label').firstChild.textContent=d.mode==='containers'?'Containers eaten':'Servings eaten';}updateCalculator(f);}if(f.id==='portion-form')updatePortion();if(f.id==='describe-form')ui.description=f.elements.description.value;});
document.addEventListener('change',async event=>{try{const el=event.target;if(el.id==='theme-select'){commit(s=>s.preferences.theme=el.value);render();}if(el.name==='template')updateRestaurant();if(el.closest('#batch-form')&&['name','yield'].includes(el.name)){const f=$('#batch-form');commit(s=>{s.draft.name=f.elements.name.value;s.draft.yield=f.elements.yield.value;});}if(el.id==='import-file'&&el.files?.[0]){const file=el.files[0];if(file.size>10*1024*1024)throw new Error('Choose a backup smaller than 10 MB.');importCandidate=validateBackup(JSON.parse(await file.text()));showDialog('Replace your current log?',`<p>This backup contains ${Object.keys(importCandidate.days).length} saved days and ${importCandidate.batches.length} batches. Import replaces all current tracking data.</p>${button('Keep current data','close','primary')}${button('Export current backup','export','secondary full')}${button('Replace with this backup','confirm-import','text-button danger')}`);}}catch(e){errorMessage(e);}});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});window.addEventListener('appinstalled',()=>{installPrompt=null;toast('Welcome home. 🍊');});
window.addEventListener('online',()=>render());window.addEventListener('offline',()=>render());
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY)toast('Your log changed in another tab. Refresh data in Settings.');});
let lastToday=localDate();document.addEventListener('visibilitychange',()=>{if(!document.hidden&&lastToday!==localDate()){if(ui.date===lastToday)ui.date=localDate();lastToday=localDate();render();}});
if('serviceWorker' in navigator&&window.isSecureContext){navigator.serviceWorker.register(new URL('../sw.js',import.meta.url)).then(reg=>{swRegistration=reg;}).catch(()=>toast('Offline setup isn’t available yet. The app still works online.'));let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!refreshing){refreshing=true;location.reload();}});}
const initial=location.hash.slice(1);if(['today','add','cook','dinner','calendar','settings'].includes(initial))ui.page=initial;render();
if(storageError)toast('Saved data needs attention. Open Settings.');
else if(!state.onboarded)showDialog('A little less. A little clarity.',`<div class="welcome-orange" aria-hidden="true">🍊</div><p>Your sodium, one meal at a time. Set the daily limit you follow to get started.</p><form id="onboarding-form">${input('goal','My daily sodium limit (mg)',state.goal,{type:'number',min:1,step:1})}<p class="muted small">You can change this later. Your private log stays on this device.</p>${submit('Make myself at home')}</form>`);
