// Deliberately small offline estimates. These are editable planning templates,
// not restaurant measurements, personalized dietary advice, or a live menu feed.
export const RESTAURANT_TEMPLATES=[
  {id:'bowl',name:'Chicken rice bowl',aliases:['burrito bowl','rice bowl','chipotle'],mg:1020,low:750,high:1500,portion:'1 bowl',basis:'Chicken, white rice, black beans and fajita vegetables; no salsa, cheese or dressing. Reference sum: 310 + 350 + 210 + 150 mg. Actual portions and recipes vary.',source:'Chipotle published US component reference (July 2022)',url:'https://www.chipotle.com/content/dam/poc/order/nutrition-files/PaperMenu_STANDARD_NoPricing_120221_us.pdf'},
  {id:'burrito',name:'Chicken burrito',aliases:['burrito'],mg:1620,low:1200,high:2200,portion:'1 burrito',basis:'The same chicken, white rice, black beans and vegetable bowl, plus a 600 mg tortilla. No salsa, cheese or dressing. Older reference; verify the restaurant’s current menu.',source:'Chipotle published US component reference (July 2022)',url:'https://www.chipotle.com/content/dam/poc/order/nutrition-files/PaperMenu_STANDARD_NoPricing_120221_us.pdf'},
  {id:'custom',name:'Another restaurant dish',aliases:[],mg:null,basis:'Enter the restaurant’s published sodium, or an estimate you want to use. Unknown sodium is never treated as zero.'}
];
export const DINNER_IDEAS=[
  {id:'lemon-chicken',name:'Lemon chicken & rice',emoji:'🍋',minutes:25,mg:200,low:130,high:350,vegetarian:false,ingredients:['150 g unbrined chicken breast','1 cup cooked unsalted rice','1 cup broccoli','Lemon, olive oil and herbs; no added salt'],steps:'Roast or pan-cook the chicken and broccoli with oil, lemon and herbs. Serve over unsalted rice. Avoid brined chicken and bottled sauces.',basis:'Planning estimate from typical unsalted ingredient values. Brands, portion sizes and seasoning change sodium.'},
  {id:'chickpea',name:'Chickpea & avocado bowl',emoji:'🥑',minutes:15,mg:120,low:50,high:250,vegetarian:true,ingredients:['¾ cup no-salt-added chickpeas','½ avocado','½ cup cooked unsalted quinoa','Cucumber, lemon and olive oil; no added salt'],steps:'Combine the chickpeas and quinoa with chopped cucumber and avocado. Dress with lemon and oil. Check chickpea labels; regular canned chickpeas change the total.',basis:'Planning estimate for no-salt-added ingredients, not a verified branded recipe.'},
  {id:'salmon',name:'Herby salmon & potatoes',emoji:'🥔',minutes:30,mg:180,low:100,high:320,vegetarian:false,ingredients:['150 g fresh, unbrined salmon','1 medium potato','1 cup green beans','Olive oil, garlic and herbs; no added salt'],steps:'Roast the salmon, cubed potato and beans with olive oil and herbs. Use fresh salmon rather than smoked or pre-seasoned fish.',basis:'Planning estimate for unsalted ingredients. Check the fish and seasoning labels.'}
];
